<a href="https://colab.research.google.com/github/AaryanSahu/NLP/blob/main/NLP_submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hindi_15.tsv to hindi_15 (1).tsv


In [ ]:
import pandas as pd

# read in the data as a Pandas DataFrame
df = pd.read_csv('hindi_15.tsv', sep='\t', header=None, names=['text_id', 'text', 'task_1', 'task_2', 'task_3'])

# create a new DataFrame with just the text_id and text columns
df_text = df[['text_id', 'text']].copy()

# convert the task_1, task_2, and task_3 columns to 0s and 1s
df_tasks = pd.get_dummies(df[['task_1', 'task_2', 'task_3']])

# concatenate the text and task DataFrames
df = pd.concat([df_text, df_tasks], axis=1)

# print the new DataFrame



In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_1_task_1  task_2_NONE  task_2_PRFN  \
0           0           0              1            0            0   
1           0           1              0            1            0   
2           1           0              0            0            1   
3           1           0              0            0            1   
4           0           1              0            1            0   

   task_2_task_2  task_3_NONE  task_3_TIN  task_3_UNT  task_3_task_3  
0              1            0           0           0              1  
1              0            1           0           0              0  
2              0            0           0           1              0  
3              0            0           1           0              0  
4              0            1           0           0              0

In [ ]:
df = df.drop(columns=['task_2_NONE','task_3_NONE',])

In [ ]:
df = df.drop(columns=['task_1_task_1','task_2_task_2',"task_3_task_3"])

In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  
0           0           0            0           0           0  
1           0           1            0           0           0  
2           1           0            1           0           1  
3           1           0            1           1           0  
4           0           1            0           0           0

In [ ]:
df.insert(loc=4, column='task_2_HATE', value=0)


In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  
0           0           0            0            0           0           0  
1           0           1            0            0           0           0  
2           1           0            0            1           0           1  
3           1           0            0            1           1           0  
4           0           1            0            0           0           0

In [ ]:
df.drop(index=0)


text_id                                               text  \
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  
1            0           1            0            0           0           0  
2            1           0            0            1           0           1  
3            1           0            0            1           1           0  
4            0           1            0            0           0           0  
5            0           1            0            0           0           0  
6            0           1            0            0           0           0  
7            0           1            0            0           0           0  
8            0           1            0            0           0           0  
9            0           1            0            0           0           0  
10           0           1            0            0           0           0  
11           0           1            0            0           0           0  
12           0           1            0            0           0           0  
13           0           1            0            0           0           0  
14           0           1            0            0           0           0  
15           0           1            0            0           0           0

In [ ]:
pip install Keras-Preprocessing


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install transformers
import pandas as pd
import numpy as np
import tensorflow as tf
import torch
import keras
from torch.nn import BCEWithLogitsLoss, BCELoss
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from keras_preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix, f1_score, accuracy_score
import pickle
from transformers import *
from tqdm import tqdm, trange
from ast import literal_eval

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [ ]:
device

device(type='cuda')

In [ ]:
print('Unique comments: ', df.text.nunique() == df.shape[0])
print('Null values: ', df.isnull().values.any())
# df[df.isna().any(axis=1)]

Unique comments:  True
Null values:  False


In [ ]:
print('average sentence length: ', df.text.str.split().str.len().mean())
print('stdev sentence length: ', df.text.str.split().str.len().std())


average sentence length:  24.9375
stdev sentence length:  14.484330613919765


In [ ]:
cols = df.columns
label_cols = list(cols[2:])
num_labels = len(label_cols)
print('Label columns: ', label_cols)


Label columns:  ['task_1_HOF', 'task_1_NOT', 'task_2_HATE', 'task_2_PRFN', 'task_3_TIN', 'task_3_UNT']


In [ ]:
df1 = df.sample(frac=1).reset_index(drop=True) #shuffle rows


In [ ]:
df1

text_id                                               text  \
0         text_id                                               text   
1   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3   hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
4   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
5   hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
6   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
7    hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
8   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
9    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
10  hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12  hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
13  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
14  hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  
0            0           0            0            0           0           0  
1            0           1            0            0           0           0  
2            1           0            0            1           0           1  
3            0           1            0            0           0           0  
4            0           1            0            0           0           0  
5            0           1            0            0           0           0  
6            0           1            0            0           0           0  
7            0           1            0            0           0           0  
8            0           1            0            0           0           0  
9            1           0            0            1           1           0  
10           0           1            0            0           0           0  
11           0           1            0            0           0           0  
12           0           1            0            0           0           0  
13           0           1            0            0           0           0  
14           0           1            0            0           0           0  
15           0           1            0            0           0           0

In [ ]:
df['one_hot_labels'] = list(df[label_cols].values)
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  \
0           0           0            0            0           0           0   
1           0           1            0            0           0           0   
2           1           0            0            1           0           1   
3           1           0            0            1           1           0   
4           0           1            0            0           0           0   

       one_hot_labels  
0  [0, 0, 0, 0, 0, 0]  
1  [0, 1, 0, 0, 0, 0]  
2  [1, 0, 0, 1, 0, 1]  
3  [1, 0, 0, 1, 1, 0]  
4  [0, 1, 0, 0, 0, 0]

In [ ]:
labels = list(df.one_hot_labels.values)
comments = list(df.text.values)

In [ ]:
labels

[array([0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 1, 0, 1]),
 array([1, 0, 0, 1, 1, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0])]

In [ ]:
# Importing stock ml libraries
import numpy as np
import pandas as pd
from sklearn import metrics
import transformers
import torch
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from transformers import BertTokenizer, BertModel, BertConfig

In [ ]:
df

text_id                                               text  \
0         text_id                                               text   
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  \
0            0           0            0            0           0           0   
1            0           1            0            0           0           0   
2            1           0            0            1           0           1   
3            1           0            0            1           1           0   
4            0           1            0            0           0           0   
5            0           1            0            0           0           0   
6            0           1            0            0           0           0   
7            0           1            0            0           0           0   
8            0           1            0            0           0           0   
9            0           1            0            0           0           0   
10           0           1            0            0           0           0   
11           0           1            0            0           0           0   
12           0           1            0            0           0           0   
13           0           1            0            0           0           0   
14           0           1            0            0           0           0   
15           0           1            0            0           0           0   

        one_hot_labels  
0   [0, 0, 0, 0, 0, 0]  
1   [0, 1, 0, 0, 0, 0]  
2   [1, 0, 0, 1, 0, 1]  
3   [1, 0, 0, 1, 1, 0]  
4   [0, 1, 0, 0, 0, 0]  
5   [0, 1, 0, 0, 0, 0]  
6   [0, 1, 0, 0, 0, 0]  
7   [0, 1, 0, 0, 0, 0]  
8   [0, 1, 0, 0, 0, 0]  
9   [0, 1, 0, 0, 0, 0]  
10  [0, 1, 0, 0, 0, 0]  
11  [0, 1, 0, 0, 0, 0]  
12  [0, 1, 0, 0, 0, 0]  
13  [0, 1, 0, 0, 0, 0]  
14  [0, 1, 0, 0, 0, 0]  
15  [0, 1, 0, 0, 0, 0]

In [ ]:
df.rename(columns = {'text':'comment_text',
                              'one_hot_labels':'list'}, inplace = True)

In [ ]:
df

text_id                                       comment_text  \
0         text_id                                               text   
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  \
0            0           0            0            0           0           0   
1            0           1            0            0           0           0   
2            1           0            0            1           0           1   
3            1           0            0            1           1           0   
4            0           1            0            0           0           0   
5            0           1            0            0           0           0   
6            0           1            0            0           0           0   
7            0           1            0            0           0           0   
8            0           1            0            0           0           0   
9            0           1            0            0           0           0   
10           0           1            0            0           0           0   
11           0           1            0            0           0           0   
12           0           1            0            0           0           0   
13           0           1            0            0           0           0   
14           0           1            0            0           0           0   
15           0           1            0            0           0           0   

                  list  
0   [0, 0, 0, 0, 0, 0]  
1   [0, 1, 0, 0, 0, 0]  
2   [1, 0, 0, 1, 0, 1]  
3   [1, 0, 0, 1, 1, 0]  
4   [0, 1, 0, 0, 0, 0]  
5   [0, 1, 0, 0, 0, 0]  
6   [0, 1, 0, 0, 0, 0]  
7   [0, 1, 0, 0, 0, 0]  
8   [0, 1, 0, 0, 0, 0]  
9   [0, 1, 0, 0, 0, 0]  
10  [0, 1, 0, 0, 0, 0]  
11  [0, 1, 0, 0, 0, 0]  
12  [0, 1, 0, 0, 0, 0]  
13  [0, 1, 0, 0, 0, 0]  
14  [0, 1, 0, 0, 0, 0]  
15  [0, 1, 0, 0, 0, 0]

In [ ]:
df=df.iloc[1:, :]

In [ ]:
df

text_id                                       comment_text  \
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_HATE  task_2_PRFN  task_3_TIN  task_3_UNT  \
1            0           1            0            0           0           0   
2            1           0            0            1           0           1   
3            1           0            0            1           1           0   
4            0           1            0            0           0           0   
5            0           1            0            0           0           0   
6            0           1            0            0           0           0   
7            0           1            0            0           0           0   
8            0           1            0            0           0           0   
9            0           1            0            0           0           0   
10           0           1            0            0           0           0   
11           0           1            0            0           0           0   
12           0           1            0            0           0           0   
13           0           1            0            0           0           0   
14           0           1            0            0           0           0   
15           0           1            0            0           0           0   

                  list  
1   [0, 1, 0, 0, 0, 0]  
2   [1, 0, 0, 1, 0, 1]  
3   [1, 0, 0, 1, 1, 0]  
4   [0, 1, 0, 0, 0, 0]  
5   [0, 1, 0, 0, 0, 0]  
6   [0, 1, 0, 0, 0, 0]  
7   [0, 1, 0, 0, 0, 0]  
8   [0, 1, 0, 0, 0, 0]  
9   [0, 1, 0, 0, 0, 0]  
10  [0, 1, 0, 0, 0, 0]  
11  [0, 1, 0, 0, 0, 0]  
12  [0, 1, 0, 0, 0, 0]  
13  [0, 1, 0, 0, 0, 0]  
14  [0, 1, 0, 0, 0, 0]  
15  [0, 1, 0, 0, 0, 0]

In [ ]:
# Sections of config

# Defining some key variables that will be used later on in the training
MAX_LEN = 200
TRAIN_BATCH_SIZE = 8
VALID_BATCH_SIZE = 4
EPOCHS = 1
LEARNING_RATE = 1e-05
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/vocab.txt
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/tokenizer_config.json
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/config.json
Model config BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_positio

In [ ]:
class CustomDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.data = dataframe
        self.comment_text = dataframe.comment_text
        self.targets = self.data.list
        self.max_len = max_len

    def __len__(self):
        return len(self.comment_text)

    def __getitem__(self, index):
        comment_text = str(self.comment_text[index])
        comment_text = " ".join(comment_text.split())

        inputs = self.tokenizer.encode_plus(
            comment_text,
            None,
            add_special_tokens=True,
            max_length=self.max_len,
            pad_to_max_length=True,
            return_token_type_ids=True
        )
        ids = inputs['input_ids']
        mask = inputs['attention_mask']
        token_type_ids = inputs["token_type_ids"]


        return {
            'ids': torch.tensor(ids, dtype=torch.long),
            'mask': torch.tensor(mask, dtype=torch.long),
            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
            'targets': torch.tensor(self.targets[index], dtype=torch.float)
        }


In [ ]:
new_df = df[['comment_text', 'list']].copy()
new_df.head()

comment_text                list
1  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...  [0, 1, 0, 0, 0, 0]
2  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई #शांती...  [1, 0, 0, 1, 0, 1]
3  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...  [1, 0, 0, 1, 1, 0]
4  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...  [0, 1, 0, 0, 0, 0]
5  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...  [0, 1, 0, 0, 0, 0]

In [ ]:
# Creating the dataset and dataloader for the neural network

train_size = 0.8
train_dataset=new_df.sample(frac=train_size,random_state=200)
test_dataset=new_df.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)


print("FULL Dataset: {}".format(new_df.shape))
print("TRAIN Dataset: {}".format(train_dataset.shape))
print("TEST Dataset: {}".format(test_dataset.shape))

training_set = CustomDataset(train_dataset, tokenizer, MAX_LEN)
testing_set = CustomDataset(test_dataset, tokenizer, MAX_LEN)

FULL Dataset: (15, 2)
TRAIN Dataset: (12, 2)
TEST Dataset: (3, 2)


In [ ]:
train_params = {'batch_size': TRAIN_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

test_params = {'batch_size': VALID_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

training_loader = DataLoader(training_set, **train_params)
testing_loader = DataLoader(testing_set, **test_params)


In [ ]:
# Creating the customized model, by adding a drop out and a dense layer on top of distil bert to get the final output for the model. 

class BERTClass(torch.nn.Module):
    def __init__(self):
        super(BERTClass, self).__init__()
        self.l1 = transformers.BertModel.from_pretrained('bert-base-uncased',return_dict=False)
        
        self.l2 = torch.nn.Dropout(0.3)
        self.l3 = torch.nn.Linear(768, 6)
    
    def forward(self, ids, mask, token_type_ids):
        _, output_1= self.l1(ids, attention_mask = mask, token_type_ids = token_type_ids)
        output_2 = self.l2(output_1)
        output = self.l3(output_2)
        return output

model = BERTClass()
model.to(device)

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/config.json
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "return_dict": false,
  "transformers_version": "4.29.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/pytorch_model.bin
Some we

BERTClass(
  (l1): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [ ]:
def loss_fn(outputs, targets):
    return torch.nn.BCEWithLogitsLoss()(outputs, targets)

In [ ]:
optimizer = torch.optim.Adam(params =  model.parameters(), lr=LEARNING_RATE)

In [ ]:
def train(epoch):
    model.train()
    for _,data in enumerate(training_loader, 0):
        ids = data['ids'].to(device, dtype = torch.long)
        mask = data['mask'].to(device, dtype = torch.long)
        token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
        targets = data['targets'].to(device, dtype = torch.float)

        outputs = model(ids, mask, token_type_ids)

        optimizer.zero_grad()
        loss = loss_fn(outputs, targets)
        if _%5000==0:
            print(f'Epoch: {epoch}, Loss:  {loss.item()}')
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


In [ ]:
for epoch in range(EPOCHS):
    train(epoch)

Epoch: 0, Loss:  0.6852022409439087


In [ ]:
def validation(epoch):
    model.eval()
    fin_targets=[]
    fin_outputs=[]
    with torch.no_grad():
        for _, data in enumerate(testing_loader, 0):
            ids = data['ids'].to(device, dtype = torch.long)
            mask = data['mask'].to(device, dtype = torch.long)
            token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
            targets = data['targets'].to(device, dtype = torch.float)
            outputs = model(ids, mask, token_type_ids)
            fin_targets.extend(targets.cpu().detach().numpy().tolist())
            fin_outputs.extend(torch.sigmoid(outputs).cpu().detach().numpy().tolist())
    return fin_outputs, fin_targets


In [ ]:
for epoch in range(EPOCHS):
    outputs, targets = validation(epoch)
    outputs = np.array(outputs) >= 0.5
    accuracy = metrics.accuracy_score(targets, outputs)
    f1_score_micro = metrics.f1_score(targets, outputs, average='micro')
    f1_score_macro = metrics.f1_score(targets, outputs, average='macro')
    print(f"Accuracy Score = {accuracy}")
    print(f"F1 Score (Micro) = {f1_score_micro}")
    print(f"F1 Score (Macro) = {f1_score_macro}")


Accuracy Score = 0.0
F1 Score (Micro) = 0.4
F1 Score (Macro) = 0.16666666666666666


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


In [ ]:
max_length = 100
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True) # tokenizer
encodings = tokenizer.batch_encode_plus(comments,max_length=max_length,pad_to_max_length=True) # tokenizer's encoding method
print('tokenizer outputs: ', encodings.keys())


loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/vocab.txt
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/tokenizer_config.json


loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/config.json
Model config BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.29.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defau

tokenizer outputs:  dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2364: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [ ]:
input_ids = encodings['input_ids'] # tokenized and encoded sentences
token_type_ids = encodings['token_type_ids'] # token type ids
attention_masks = encodings['attention_mask'] # attention masks

In [ ]:
# Identifying indices of 'one_hot_labels' entries that only occur once - this will allow us to stratify split our training data later
label_counts = df.one_hot_labels.astype(str).value_counts()
one_freq = label_counts[label_counts==1].keys()
one_freq_idxs = sorted(list(df[df.one_hot_labels.astype(str).isin(one_freq)].index), reverse=True)
print('df label indices with only one instance: ', one_freq_idxs)


df label indices with only one instance:  [3, 2, 0]


In [ ]:
# Gathering single instance inputs to force into the training set after stratified split
one_freq_input_ids = [input_ids.pop(i) for i in one_freq_idxs]
one_freq_token_types = [token_type_ids.pop(i) for i in one_freq_idxs]
one_freq_attention_masks = [attention_masks.pop(i) for i in one_freq_idxs]
one_freq_labels = [labels.pop(i) for i in one_freq_idxs]

In [ ]:
# Use train_test_split to split our data into train and validation sets

train_inputs, validation_inputs, train_labels, validation_labels, train_token_types, validation_token_types, train_masks, validation_masks = train_test_split(input_ids, labels, token_type_ids,attention_masks,
                                                            random_state=2020, test_size=0.10, stratify = labels)

# Add one frequency data to train data
train_inputs.extend(one_freq_input_ids)
train_labels.extend(one_freq_labels)
train_masks.extend(one_freq_attention_masks)
train_token_types.extend(one_freq_token_types)

# Convert all of our data into torch tensors, the required datatype for our model
train_inputs = torch.tensor(train_inputs)
train_labels = torch.tensor(train_labels)
train_masks = torch.tensor(train_masks)
train_token_types = torch.tensor(train_token_types)

validation_inputs = torch.tensor(validation_inputs)
validation_labels = torch.tensor(validation_labels)
validation_masks = torch.tensor(validation_masks)
validation_token_types = torch.tensor(validation_token_types)

<ipython-input-29-8effe635eb5d>:14: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  train_labels = torch.tensor(train_labels)


In [ ]:
# Select a batch size for training. For fine-tuning with XLNet, the authors recommend a batch size of 32, 48, or 128. We will use 32 here to avoid memory issues.
batch_size = 32

# Create an iterator of our data with torch DataLoader. This helps save on memory during training because, unlike a for loop, 
# with an iterator the entire dataset does not need to be loaded into memory

train_data = TensorDataset(train_inputs, train_masks, train_labels, train_token_types)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels, validation_token_types)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)

In [ ]:
torch.save(validation_dataloader,'validation_data_loader')
torch.save(train_dataloader,'train_data_loader')

In [ ]:
# Load model, the pretrained model will include a single linear classification layer on top for classification. 
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=num_labels)
outputs = model(**inputs, return_dict=False)
model.cuda()

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/config.json
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.29.2",
  "type_vo

loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/pytorch_model.bin
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [ ]:
# setting custom optimization parameters. You may implement a scheduler here as well.
param_optimizer = list(model.named_parameters())
no_decay = ['bias', 'gamma', 'beta']
optimizer_grouped_parameters = [
    {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)],
     'weight_decay_rate': 0.01},
    {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)],
     'weight_decay_rate': 0.0}
]

In [ ]:
optimizer = AdamW(optimizer_grouped_parameters,lr=2e-5,correct_bias=True)
# optimizer = AdamW(model.parameters(),lr=2e-5)  # Default optimization

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:407: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
# Store our loss and accuracy for plotting
train_loss_set = []

# Number of training epochs (authors recommend between 2 and 4)
epochs = 3

# trange is a tqdm wrapper around the normal python range
for _ in trange(epochs, desc="Epoch"):

  # Training
  
  # Set our model to training mode (as opposed to evaluation mode)
  model.train()

  # Tracking variables
  tr_loss = 0 #running loss
  nb_tr_examples, nb_tr_steps = 0, 0
  
  # Train the data for one epoch
  for step, batch in enumerate(train_dataloader):
    # Add batch to GPU
    batch = tuple(t.to(device) for t in batch)
    # Unpack the inputs from our dataloader
    b_input_ids, b_input_mask, b_labels, b_token_types = batch
    # Clear out the gradients (by default they accumulate)
    optimizer.zero_grad()

    # # Forward pass for multiclass classification
    # outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
    # loss = outputs[0]
    # logits = outputs[1]

    # Forward pass for multilabel classification
    outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask)
    logits = outputs[0]
    loss_func = BCEWithLogitsLoss() 
    loss = loss_func(logits.view(-1,num_labels),b_labels.type_as(logits).view(-1,num_labels)) #convert labels to float for calculation
    # loss_func = BCELoss() 
    # loss = loss_func(torch.sigmoid(logits.view(-1,num_labels)),b_labels.type_as(logits).view(-1,num_labels)) #convert labels to float for calculation
    train_loss_set.append(loss.item())    

    # Backward pass
    loss.backward()
    # Update parameters and take a step using the computed gradient
    optimizer.step()
    # scheduler.step()
    # Update tracking variables
    tr_loss += loss.item()
    nb_tr_examples += b_input_ids.size(0)
    nb_tr_steps += 1

  print("Train loss: {}".format(tr_loss/nb_tr_steps))

###############################################################################

  # Validation

  # Put model in evaluation mode to evaluate loss on the validation set
  model.eval()

  # Variables to gather full output
  logit_preds,true_labels,pred_labels,tokenized_texts = [],[],[],[]

  # Predict
  for i, batch in enumerate(validation_dataloader):
    batch = tuple(t.to(device) for t in batch)
    # Unpack the inputs from our dataloader
    b_input_ids, b_input_mask, b_labels, b_token_types = batch
    with torch.no_grad():
      # Forward pass
      outs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask)
      b_logit_pred = outs[0]
      pred_label = torch.sigmoid(b_logit_pred)

      b_logit_pred = b_logit_pred.detach().cpu().numpy()
      pred_label = pred_label.to('cpu').numpy()
      b_labels = b_labels.to('cpu').numpy()

    tokenized_texts.append(b_input_ids)
    logit_preds.append(b_logit_pred)
    true_labels.append(b_labels)
    pred_labels.append(pred_label)

  # Flatten outputs
  pred_labels = [item for sublist in pred_labels for item in sublist]
  true_labels = [item for sublist in true_labels for item in sublist]

  # Calculate Accuracy
  threshold = 0.50
  pred_bools = [pl>threshold for pl in pred_labels]
  true_bools = [tl==1 for tl in true_labels]
  val_f1_accuracy = f1_score(true_bools,pred_bools,average='micro')*100
  val_flat_accuracy = accuracy_score(true_bools, pred_bools)*100

  print('F1 Validation Accuracy: ', val_f1_accuracy)
  print('Flat Validation Accuracy: ', val_flat_accuracy)

Epoch:  33%|███▎      | 1/3 [00:03<00:07,  3.73s/it]

Train loss: 0.636246919631958
F1 Validation Accuracy:  50.0
Flat Validation Accuracy:  0.0


Epoch:  67%|██████▋   | 2/3 [00:04<00:01,  1.71s/it]

Train loss: 0.612366795539856
F1 Validation Accuracy:  66.66666666666666
Flat Validation Accuracy:  0.0


Epoch: 100%|██████████| 3/3 [00:04<00:00,  1.44s/it]

Train loss: 0.5869219303131104
F1 Validation Accuracy:  100.0
Flat Validation Accuracy:  100.0


In [ ]:
torch.save(model.state_dict(), 'bert_model_toxic')

In [ ]:
# Test

# Put model in evaluation mode to evaluate loss on the validation set
model.eval()

#track variables
logit_preds,true_labels,pred_labels,tokenized_texts = [],[],[],[]

# Predict
for i, batch in enumerate(test_dataloader):
  batch = tuple(t.to(device) for t in batch)
  # Unpack the inputs from our dataloader
  b_input_ids, b_input_mask, b_labels, b_token_types = batch
  with torch.no_grad():
    # Forward pass
    outs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask)
    b_logit_pred = outs[0]
    pred_label = torch.sigmoid(b_logit_pred)

    b_logit_pred = b_logit_pred.detach().cpu().numpy()
    pred_label = pred_label.to('cpu').numpy()
    b_labels = b_labels.to('cpu').numpy()

  tokenized_texts.append(b_input_ids)
  logit_preds.append(b_logit_pred)
  true_labels.append(b_labels)
  pred_labels.append(pred_label)

# Flatten outputs
tokenized_texts = [item for sublist in tokenized_texts for item in sublist]
pred_labels = [item for sublist in pred_labels for item in sublist]
true_labels = [item for sublist in true_labels for item in sublist]
# Converting flattened binary values to boolean values
true_bools = [tl==1 for tl in true_labels]

NameError: ignored